# Generated by Django 3.1.4 on 2020-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=39)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sno',
            field=models.IntegerField(auto_created=True, default=2),
            preserve_default=False,
        ),
    ]
