# Generated by Django 3.1.4 on 2020-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0002_auto_20201212_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static/images/background1.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='sno',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
