# Generated by Django 3.1.4 on 2020-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0003_auto_20201212_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
