# Generated by Django 3.1.4 on 2020-12-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0004_auto_20201214_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
