# Generated by Django 3.1.4 on 2020-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=35)),
                ('que', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
