# Generated by Django 3.1.4 on 2021-01-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childapp', '0008_auto_20210102_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='s_no',
            new_name='contact_s_no',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sno',
            new_name='post_sno',
        ),
        migrations.RenameField(
            model_name='ques',
            old_name='s_no',
            new_name='que_s_no',
        ),
    ]
